baseurl: ""
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
permalink: pretty
title: "Mac OS Forge"
url: "https://www.macosforge.org"
